ProjectCatelogMVC/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProductCatDAL.Models;
using ProductCateBBL.Repositories.interfaces;
using ProductCatelogPL.ViewModel;
using System.Drawing.Printing;
using System.Security.Claims;

namespace ProductCatelogPL.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly UserManager<IdentityUser> userManager;
        public readonly IMapper Imapper;
        public ProductController(IUnitOfWork _unitOfWork, UserManager<IdentityUser> _userManager,  IMapper _Imapper)
        {
            this.unitOfWork = _unitOfWork;
            this.userManager = _userManager;
            this.Imapper = _Imapper;
        }

        public IActionResult Details(int id)
        {
            var product = unitOfWork.product.getByIdWithInclue(id);

            var prdVM = Imapper.Map<ProductVM>(product);
        
            return View(prdVM);
        }
        public IActionResult Index()
        {
            List<ProductVM> productsVM = new List<ProductVM>();
            List<Category> categories = unitOfWork.category.getAll();

            var products = unitOfWork.product.getAll("Category");
            ViewData["Categories"] = categories;

            foreach (var prd in products)
            {
                var prdVM = Imapper.Map<ProductVM>(prd);
                productsVM.Add(prdVM);
            }

            return View(productsVM);
        }

        public IActionResult Create()
        {
            List<Category> categories = unitOfWork.category.getAll();
            ViewData["Categories"] = categories;
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductVM productVm)
        {
      

            if (ModelState.IsValid && productVm.CategoryId != 0)
            {

                var product = Imapper.Map<Product>(productVm);
                
                unitOfWork.product.add(product);
                unitOfWork.save();
                return RedirectToAction("Index");
            }
            else
            {
                List<Category> categories = unitOfWork.category.getAll();
                ViewData["Categories"] = categories;
                return View(productVm);
            }
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            else
            {
                var product = unitOfWork.product.getById(Id);
                if (product == null)
                    return NotFound();
                
                var productVm = Imapper.Map<ProductVM>(product);
                List<Category> categories = unitOfWork.category.getAll();
                ViewData["Categories"] = categories;
                return View( productVm);
            }

        }
        [HttpPost]
        public IActionResult Edit(ProductVM productVm, [FromRoute] int id)
        {
            if (ModelState.IsValid && productVm.CategoryId != 0)
            {
                var productMapping = Imapper.Map<Product>(productVm);

               
                unitOfWork.product.update(productMapping);
                unitOfWork.save();
                return RedirectToAction("index");
            }
            else
            {
                List<Category> categories = unitOfWork.category.getAll();
                ViewData["Categories"] = categories;
                return View( productVm);
            }
        }


        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var product = unitOfWork.product.getById(Id);
            if (product != null)
            {
                unitOfWork.product.delete(Id);
                unitOfWork.save();
                return RedirectToAction("index");
            }
               

            return NotFound();
        }

        public IActionResult GetFilteredProductsAdmin(int categoryId)
        {
            List<Product> filteredProducts;
            List<ProductVM> productsVM = new List<ProductVM>();

            if (categoryId > 0)
            {
                filteredProducts = unitOfWork.product.getByCategory(categoryId);
            }
            else
            {
                filteredProducts = unitOfWork.product.getAll();
            }

            foreach (var prd in filteredProducts)
            {
                var prdVM = Imapper.Map<ProductVM>(prd);
                productsVM.Add(prdVM);
            }
            return PartialView("_ShowAdminProductPartial", productsVM);
        }

    }
}

ProjectCatelogMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductCategory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ProductCategory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                   
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Product" asp-action="Index">Products</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Account" asp-action="AddAdmin">Add Admin</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>

                    <partial name="_loginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="mb-5 pb-5">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>